


import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Ale
 */
public class MenuInicio extends javax.swing.JFrame {

    /**
     * Creates new form MenuInicio
     */
    private Fuentes tipoFuente;
    private Fondo fondito = new Fondo();
    //constructor menu de inicio, pasamos el temporizador, el sonido y los tipos de fuentes, estos se pasarán por todos los constructores, cambiando
    //de todos.
    public MenuInicio() {
        initComponents();
        ReproducirSonido("musica10(final).wav");
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        contenedorMenu.setOpaque(false);
        tipoFuente = new Fuentes();
        this.setIconImage(new ImageIcon(getClass().getResource("logo2.png")).getImage());
        this.setLocationRelativeTo(this);
        botonEmpezar.setFont(tipoFuente.fuente(tipoFuente.staypix, 0, 40));
        botonReglas.setFont(tipoFuente.fuente(tipoFuente.staypix, 0, 40));
        botonMarcador.setFont(tipoFuente.fuente(tipoFuente.staypix, 0, 40));
        botonSalir.setFont(tipoFuente.fuente(tipoFuente.staypix, 0, 40));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new Fondo();
        contenedorMenu = new javax.swing.JPanel();
        botonEmpezar = new javax.swing.JButton();
        botonReglas = new javax.swing.JButton();
        botonMarcador = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lettermania");

        jPanel1.setBackground(new java.awt.Color(51, 153, 0));

        contenedorMenu.setBackground(new java.awt.Color(153, 153, 153));

        botonEmpezar.setText("EMPEZAR");
        botonEmpezar.setBorder(null);
        botonEmpezar.setContentAreaFilled(false);
        botonEmpezar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEmpezar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                botonEmpezarMouseMoved(evt);
            }
        });
        botonEmpezar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonEmpezarMouseExited(evt);
            }
        });
        botonEmpezar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEmpezarActionPerformed(evt);
            }
        });

        botonReglas.setText("REGLAS");
        botonReglas.setBorder(null);
        botonReglas.setContentAreaFilled(false);
        botonReglas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonReglas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                botonReglasMouseMoved(evt);
            }
        });
        botonReglas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonReglasMouseExited(evt);
            }
        });
        botonReglas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReglasActionPerformed(evt);
            }
        });

        botonMarcador.setText("TOP SCORE");
        botonMarcador.setBorder(null);
        botonMarcador.setContentAreaFilled(false);
        botonMarcador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonMarcador.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                botonMarcadorMouseMoved(evt);
            }
        });
        botonMarcador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonMarcadorMouseExited(evt);
            }
        });
        botonMarcador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMarcadorActionPerformed(evt);
            }
        });

        botonSalir.setText("SALIR");
        botonSalir.setBorder(null);
        botonSalir.setContentAreaFilled(false);
        botonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonSalir.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                botonSalirMouseMoved(evt);
            }
        });
        botonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonSalirMouseExited(evt);
            }
        });
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconoSel.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel1MouseReleased(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconoSel.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconoSel.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconoSel.png"))); // NOI18N

        javax.swing.GroupLayout contenedorMenuLayout = new javax.swing.GroupLayout(contenedorMenu);
        contenedorMenu.setLayout(contenedorMenuLayout);
        contenedorMenuLayout.setHorizontalGroup(
            contenedorMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorMenuLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(5, 5, 5)
                .addComponent(botonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(contenedorMenuLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(botonEmpezar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(contenedorMenuLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(5, 5, 5)
                .addComponent(botonReglas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(contenedorMenuLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(5, 5, 5)
                .addComponent(botonMarcador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        contenedorMenuLayout.setVerticalGroup(
            contenedorMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorMenuLayout.createSequentialGroup()
                .addGroup(contenedorMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonEmpezar)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contenedorMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonReglas)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contenedorMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonMarcador)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(contenedorMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonSalir)
                    .addComponent(jLabel4)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(399, Short.MAX_VALUE)
                .addComponent(contenedorMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(403, 403, 403))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(364, Short.MAX_VALUE)
                .addComponent(contenedorMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//Botón para iniciar el juego
    private void botonEmpezarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEmpezarActionPerformed
        // TODO add your handling code here:
        SeleccionPersonaje a = new SeleccionPersonaje();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonEmpezarActionPerformed
//Abrir base de datos
    private void botonMarcadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMarcadorActionPerformed
        // TODO add your handling code here:
        Ranking puntos = new Ranking();
        puntos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonMarcadorActionPerformed
//Salir
    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_botonSalirActionPerformed
//Cuando se pasa el ratón por encima, muestra un label, así en todos los "MouseMoved"
    private void botonEmpezarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEmpezarMouseMoved
        // TODO add your handling code here:      
         jLabel1.setVisible(true);
         botonEmpezar.setForeground(Color.yellow);
        
    }//GEN-LAST:event_botonEmpezarMouseMoved

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseReleased

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jLabel1MouseExited
//Cuando el ratón se quita de encima, se oculta, así en todos los MOuseExited.
    private void botonEmpezarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEmpezarMouseExited
        // TODO add your handling code here:
         jLabel1.setVisible(false);
         botonEmpezar.setForeground(Color.black);
    }//GEN-LAST:event_botonEmpezarMouseExited

    private void botonReglasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonReglasMouseMoved
        // TODO add your handling code here:
         jLabel2.setVisible(true);
         botonReglas.setForeground(Color.yellow);
    }//GEN-LAST:event_botonReglasMouseMoved

    private void botonReglasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonReglasMouseExited
        // TODO add your handling code here:
         jLabel2.setVisible(false);
         botonReglas.setForeground(Color.black);
    }//GEN-LAST:event_botonReglasMouseExited

    private void botonMarcadorMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMarcadorMouseMoved
        // TODO add your handling code here:
         jLabel3.setVisible(true);
         botonMarcador.setForeground(Color.yellow);
    }//GEN-LAST:event_botonMarcadorMouseMoved

    private void botonMarcadorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMarcadorMouseExited
        // TODO add your handling code here:
         jLabel3.setVisible(false);
         botonMarcador.setForeground(Color.black);
    }//GEN-LAST:event_botonMarcadorMouseExited

    private void botonSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSalirMouseExited
        // TODO add your handling code here:
         jLabel4.setVisible(false);
         botonSalir.setForeground(Color.black);
    }//GEN-LAST:event_botonSalirMouseExited

    private void botonSalirMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSalirMouseMoved
        // TODO add your handling code here:
         jLabel4.setVisible(true);
         botonSalir.setForeground(Color.yellow);
    }//GEN-LAST:event_botonSalirMouseMoved

    private void botonReglasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReglasActionPerformed
        // TODO add your handling code here:
       Reglas ventanaReglas = new Reglas();
       ventanaReglas.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_botonReglasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuInicio().setVisible(true);
            }
        });
    }


//Método para reproducir el audio de fondo, se crea una instancia de AudioInputStream, tras esto, con Clip, manejamos el audio.
    public void ReproducirSonido(String nombreSonido){
       try {
        AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(new File(nombreSonido).getAbsoluteFile());
        Clip clip = AudioSystem.getClip();
        clip.open(audioInputStream);
        clip.start();
       } catch(UnsupportedAudioFileException | IOException | LineUnavailableException ex) {
         System.out.println("Error al reproducir el sonido.");
       }
    }   
    
public class Fuentes{//Generar las fuentes personalizadas
    private Font font = null;
    public String staypix = "StayPix.ttf";
    
    public Font fuente(String nombreFuente, int estilo, float tamanio){
    try{
        //Cargamos la fuente
        InputStream is = getClass().getResourceAsStream(nombreFuente);
        font = Font.createFont(Font.TRUETYPE_FONT, is);
    }
    catch(Exception error){
        System.out.println("Error");
    }
    Font tfont =font.deriveFont(estilo, tamanio);
    return tfont;
}   

}

class Fondo extends JPanel{//Creamos el fondo personalizado, estableciendo imágenes
    private Image imagenFondo;
    @Override
    public void paint(Graphics g){//el método paint nos reconoce las imágenes de nuestro proyecto
        imagenFondo = new ImageIcon(getClass().getResource("fondoLettermania.png")).getImage();
        g.drawImage(imagenFondo, 0, 0, getWidth(), getHeight(), this);
        setOpaque(false);
        super.paint(g);    
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEmpezar;
    private javax.swing.JButton botonMarcador;
    private javax.swing.JButton botonReglas;
    private javax.swing.JButton botonSalir;
    private javax.swing.JPanel contenedorMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
